services:
  db:
    image: postgres:14
    container_name: lynch_area_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: LynchAreaDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - abp-network

  app:
    build: .  # CORREÇÃO AQUI
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:123@db:5432/LynchAreaDB"
    ports:
      - "3000:3000"
    networks:
      - abp-network

volumes:
  postgres_data:

networks:
  abp-network:
    driver: bridge