name: CI Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Configure environment
        run: |
          echo "DB_USER=test_user" >> .env
          echo "DB_PASSWORD=test_password" >> .env
          echo "DB_NAME=test_db" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "JWT_SECRET=test_secret" >> .env
      
      - name: Type checking
        run: npx tsc --noEmit --strict
      
      - name: Run unit tests
        run: npm test
      
      - name: Build Docker image
       